// Generated by kaido-release prepare-app-bundle.
// Review this file and add .releasedK7AobaKohoku to the App's
// BundledProductReleaseCatalogLoader.previewManifest deliberately.
import KaidoAppleAdapters

extension AppBundleProductReleaseDescriptor {
  static let releasedK7AobaKohoku = AppBundleProductReleaseDescriptor(
    resourceName: "k7-aoba-kohoku-product-release",
    resourceExtension: "json",
    expectedSHA256: "5fe54b002b7f70e4c4086eeee6328440115e6c512f3693d68ae275250831d060",
    expectedReleaseID: "shutoko.product.k7-aoba-to-kohoku.2026-07-27",
    role: .foregroundNavigation,
    guidanceAudioChoices: [],
    preDriveEvidence: nil,
    preDriveEvidenceUpdateTrustKeys: nil,
    preDriveEvidenceUpdateEndpoint: nil
  )
}
